const base = process.env.BASE_URL || 'http://127.0.0.1:8787'
const OTPAuth = await import('otpauth')

const response = await fetch(`${base}/api/health`)
if (!response.ok) throw new Error(`Health check failed: ${response.status}`)
const health = await response.json()
if (!health.ok || health.service !== 'river') throw new Error(`Unexpected health payload: ${JSON.stringify(health)}`)
const readiness = await fetch(`${base}/api/readiness`)
if (!readiness.ok || !(await readiness.json()).ready) throw new Error('Readiness check failed')

const page = await fetch(base)
if (!page.ok) throw new Error(`App shell failed: ${page.status}`)
const html = await page.text()
if (!html.includes('River')) throw new Error('App shell does not contain River branding')

console.log(`River smoke test passed (${health.model})`)

const email = `smoke-${Date.now()}@river.local`
const signup = await fetch(`${base}/api/auth/signup`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: 'River Smoke', email, password: 'smoke-password-123' }) })
if (!signup.ok) throw new Error(`Signup failed: ${signup.status}`)
const session = await signup.json()
const authHeaders = { Authorization: `Bearer ${session.token}` }
const cookieHeader = signup.headers.getSetCookie().map(cookie => cookie.split(';')[0]).join('; ')
const csrfToken = cookieHeader.split('; ').find(cookie => cookie.startsWith('river_csrf='))?.slice('river_csrf='.length)
if (!cookieHeader.includes('river_access=') || !csrfToken) throw new Error('Secure session cookies were not issued')
const cookieMe = await fetch(`${base}/api/auth/me`, { headers: { cookie: cookieHeader } })
if (!cookieMe.ok) throw new Error(`Cookie authentication failed: ${cookieMe.status}`)
const csrfBlocked = await fetch(`${base}/api/privacy/preferences`, { method: 'PUT', headers: { cookie: cookieHeader, 'content-type': 'application/json' }, body: JSON.stringify({ memory_enabled: true }) })
if (csrfBlocked.status !== 403) throw new Error(`CSRF protection failed: ${csrfBlocked.status}`)
const csrfAccepted = await fetch(`${base}/api/privacy/preferences`, { method: 'PUT', headers: { cookie: cookieHeader, 'x-csrf-token': csrfToken, 'content-type': 'application/json' }, body: JSON.stringify({ memory_enabled: true }) })
if (!csrfAccepted.ok) throw new Error(`CSRF validated request failed: ${csrfAccepted.status}`)
const threadsResponse = await fetch(`${base}/api/threads`, { headers: authHeaders })
if (!threadsResponse.ok) throw new Error(`Thread list failed: ${threadsResponse.status}`)
const initialThreads = await threadsResponse.json()
const createdThread = await fetch(`${base}/api/threads`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ title: 'Smoke thread' }) })
if (!createdThread.ok) throw new Error(`Thread create failed: ${createdThread.status}`)
const threadData = await createdThread.json()
if (!threadData.thread?.id) throw new Error('Thread was not created')
const preferences = await fetch(`${base}/api/privacy/preferences`, { headers: authHeaders })
if (!preferences.ok) throw new Error(`Privacy preferences failed: ${preferences.status}`)
const mfaSetup = await fetch(`${base}/api/auth/mfa/setup`, { method: 'POST', headers: authHeaders })
if (!mfaSetup.ok) throw new Error(`MFA setup failed: ${mfaSetup.status}`)
const mfa = await mfaSetup.json()
const otp = new OTPAuth.TOTP({ issuer: 'River', label: email, secret: OTPAuth.Secret.fromBase32(mfa.secret), algorithm: 'SHA1', digits: 6, period: 30 }).generate()
const mfaEnable = await fetch(`${base}/api/auth/mfa/enable`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ otp }) })
if (!mfaEnable.ok) throw new Error(`MFA enable failed: ${mfaEnable.status}`)
const deniedMfaLogin = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password: 'smoke-password-123' }) })
if (deniedMfaLogin.status !== 401) throw new Error('MFA was not required on login')
const allowedMfaLogin = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password: 'smoke-password-123', otp }) })
if (!allowedMfaLogin.ok) throw new Error(`MFA login failed: ${allowedMfaLogin.status}`)
const voiceSession = await fetch(`${base}/api/voice/session`, { headers: authHeaders })
const voiceConfig = await voiceSession.json()
if (!voiceSession.ok) throw new Error('Voice configuration check failed')
if (health.provider === 'groq' && (!voiceConfig.enabled || voiceConfig.provider !== 'groq')) throw new Error('Groq voice configuration failed')
if (health.provider !== 'groq' && voiceConfig.enabled !== false) throw new Error('Voice configuration fallback failed')
const voiceCall = await fetch(`${base}/api/voice/call`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ sdp: 'v=0\r\n' }) })
if (voiceCall.status !== 503) throw new Error(`Voice provider fallback failed: ${voiceCall.status}`)
if (health.provider === 'groq') {
  const emptyTranscription = await fetch(`${base}/api/voice/transcribe`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'audio/webm' }, body: Buffer.from('too-short') })
  if (emptyTranscription.status !== 400) throw new Error(`Voice input validation failed: ${emptyTranscription.status}`)
  const speech = await fetch(`${base}/api/voice/speak`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ text: 'River is ready.' }) })
  if (![200, 412].includes(speech.status)) throw new Error(`Groq speech generation failed: ${speech.status}`)
  if (speech.status === 200 && !speech.headers.get('content-type')?.startsWith('audio/')) throw new Error('Groq speech did not return audio')
}
const exported = await fetch(`${base}/api/privacy/export`, { headers: authHeaders })
if (!exported.ok) throw new Error(`Privacy export failed: ${exported.status}`)
const refreshed = await fetch(`${base}/api/auth/refresh`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ refresh_token: session.refresh_token }) })
if (!refreshed.ok) throw new Error(`Refresh failed: ${refreshed.status}`)
const chat = await fetch(`${base}/api/chat`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ thread_id: threadData.thread.id, content: 'I am thinking about planning a two-week Lisbon trip for late summer with a tiny notebook.' }) })
if (!chat.ok) throw new Error(`Chat failed: ${chat.status}`)
const chatData = await chat.json()
if (!['groq', 'gemini', 'openai', 'local-fallback'].includes(chatData.provider)) throw new Error(`Unexpected chat provider: ${chatData.provider}`)
if (health.provider !== 'local-fallback' && chatData.provider === 'local-fallback') console.warn(`Configured ${health.provider} was unavailable; River safely used the local fallback.`)
if (!chatData.proposal?.id || chatData.proposal.status !== 'pending') throw new Error('Memory proposal was not created')
const approved = await fetch(`${base}/api/memory/proposals/${chatData.proposal.id}/approve`, { method: 'POST', headers: authHeaders })
if (!approved.ok) throw new Error(`Proposal approval failed: ${approved.status}`)
const approvedData = await approved.json()
if (!approvedData.storyline?.topic) throw new Error('Approved proposal did not create a storyline')
const search = await fetch(`${base}/api/search?q=Lisbon`, { headers: authHeaders })
if (!search.ok || (await search.json()).storylines.length < 1) throw new Error('Search did not find approved memory')
const friendshipThread = await fetch(`${base}/api/threads`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ title: 'Friends' }) })
if (!friendshipThread.ok) throw new Error(`Friendship thread create failed: ${friendshipThread.status}`)
const friendship = await friendshipThread.json()
const friendshipChat = await fetch(`${base}/api/chat`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ thread_id: friendship.thread.id, content: "I feel like my friends don't like me, and it is making me question myself." }) })
if (!friendshipChat.ok) throw new Error(`Friendship chat failed: ${friendshipChat.status}`)
const friendshipData = await friendshipChat.json()
if (!friendshipData.proposal?.id || !/friend/i.test(friendshipData.proposal.topic)) throw new Error('Relationship memory proposal was not created')
const friendshipApproved = await fetch(`${base}/api/memory/proposals/${friendshipData.proposal.id}/approve`, { method: 'POST', headers: authHeaders })
if (!friendshipApproved.ok) throw new Error(`Friendship proposal approval failed: ${friendshipApproved.status}`)
const recall = await fetch(`${base}/api/chat`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ thread_id: threadData.thread.id, content: 'I want to talk about my friends.' }) })
if (!recall.ok) throw new Error(`Cross-thread recall failed: ${recall.status}`)
const recallData = await recall.json()
if (!recallData.context.some(storyline => /friend/i.test(storyline.topic))) throw new Error('Approved friendship memory was not recalled across threads')
const explicitRecall = await fetch(`${base}/api/chat`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ thread_id: friendship.thread.id, content: 'What do you remember from our prior conversations?' }) })
if (!explicitRecall.ok) throw new Error(`Explicit memory recall failed: ${explicitRecall.status}`)
const explicitRecallData = await explicitRecall.json()
if (!explicitRecallData.context.some(storyline => /friend|lisbon/i.test(`${storyline.topic} ${storyline.summary}`))) throw new Error('Direct recall request did not receive approved memories')
if (/fresh start|no prior knowledge|don.t have any prior/i.test(explicitRecallData.reply)) throw new Error('River incorrectly denied approved memories during direct recall')
if (!/remember the parts you asked me to keep/i.test(explicitRecallData.reply)) throw new Error('River did not give its grounded approved-memory recall response')
console.log('Authentication, privacy, cross-thread memory, search, and voice configuration smoke test passed')
