const base = process.env.BASE_URL || 'http://127.0.0.1:8787'
const OTPAuth = await import('otpauth')

const response = await fetch(`${base}/api/health`)
if (!response.ok) throw new Error(`Health check failed: ${response.status}`)
const health = await response.json()
if (!health.ok || health.service !== 'river') throw new Error(`Unexpected health payload: ${JSON.stringify(health)}`)
const readiness = await fetch(`${base}/api/readiness`)
if (!readiness.ok || !(await readiness.json()).ready) throw new Error('Readiness check failed')

const page = await fetch(base)
if (!page.ok) throw new Error(`App shell failed: ${page.status}`)
const html = await page.text()
if (!html.includes('River')) throw new Error('App shell does not contain River branding')

console.log(`River smoke test passed (${health.model})`)

const email = `smoke-${Date.now()}@river.local`
const signup = await fetch(`${base}/api/auth/signup`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: 'River Smoke', email, password: 'smoke-password-123' }) })
if (!signup.ok) throw new Error(`Signup failed: ${signup.status}`)
const session = await signup.json()
const authHeaders = { Authorization: `Bearer ${session.token}` }
const threadsResponse = await fetch(`${base}/api/threads`, { headers: authHeaders })
if (!threadsResponse.ok) throw new Error(`Thread list failed: ${threadsResponse.status}`)
const initialThreads = await threadsResponse.json()
const createdThread = await fetch(`${base}/api/threads`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ title: 'Smoke thread' }) })
if (!createdThread.ok) throw new Error(`Thread create failed: ${createdThread.status}`)
const threadData = await createdThread.json()
if (!threadData.thread?.id) throw new Error('Thread was not created')
const preferences = await fetch(`${base}/api/privacy/preferences`, { headers: authHeaders })
if (!preferences.ok) throw new Error(`Privacy preferences failed: ${preferences.status}`)
const mfaSetup = await fetch(`${base}/api/auth/mfa/setup`, { method: 'POST', headers: authHeaders })
if (!mfaSetup.ok) throw new Error(`MFA setup failed: ${mfaSetup.status}`)
const mfa = await mfaSetup.json()
const otp = new OTPAuth.TOTP({ issuer: 'River', label: email, secret: OTPAuth.Secret.fromBase32(mfa.secret), algorithm: 'SHA1', digits: 6, period: 30 }).generate()
const mfaEnable = await fetch(`${base}/api/auth/mfa/enable`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ otp }) })
if (!mfaEnable.ok) throw new Error(`MFA enable failed: ${mfaEnable.status}`)
const deniedMfaLogin = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password: 'smoke-password-123' }) })
if (deniedMfaLogin.status !== 401) throw new Error('MFA was not required on login')
const allowedMfaLogin = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password: 'smoke-password-123', otp }) })
if (!allowedMfaLogin.ok) throw new Error(`MFA login failed: ${allowedMfaLogin.status}`)
const voiceSession = await fetch(`${base}/api/voice/session`, { headers: authHeaders })
if (!voiceSession.ok || (await voiceSession.json()).enabled !== false) throw new Error('Voice configuration fallback failed')
const voiceCall = await fetch(`${base}/api/voice/call`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ sdp: 'v=0\r\n' }) })
if (voiceCall.status !== 503) throw new Error(`Voice provider fallback failed: ${voiceCall.status}`)
const exported = await fetch(`${base}/api/privacy/export`, { headers: authHeaders })
if (!exported.ok) throw new Error(`Privacy export failed: ${exported.status}`)
const refreshed = await fetch(`${base}/api/auth/refresh`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ refresh_token: session.refresh_token }) })
if (!refreshed.ok) throw new Error(`Refresh failed: ${refreshed.status}`)
const chat = await fetch(`${base}/api/chat`, { method: 'POST', headers: { ...authHeaders, 'content-type': 'application/json' }, body: JSON.stringify({ thread_id: threadData.thread.id, content: 'I am thinking about planning a two-week Lisbon trip for late summer with a tiny notebook.' }) })
if (!chat.ok) throw new Error(`Chat failed: ${chat.status}`)
const chatData = await chat.json()
if (!chatData.proposal?.id || chatData.proposal.status !== 'pending') throw new Error('Memory proposal was not created')
const approved = await fetch(`${base}/api/memory/proposals/${chatData.proposal.id}/approve`, { method: 'POST', headers: authHeaders })
if (!approved.ok) throw new Error(`Proposal approval failed: ${approved.status}`)
const approvedData = await approved.json()
if (!approvedData.storyline?.topic) throw new Error('Approved proposal did not create a storyline')
const search = await fetch(`${base}/api/search?q=Lisbon`, { headers: authHeaders })
if (!search.ok || (await search.json()).storylines.length < 1) throw new Error('Search did not find approved memory')
console.log('Authentication, privacy, thread, search, and voice fallback smoke test passed')
